service:
  name: omniview-backend
app: ovs-backend
org: colorfy

custom:
  aws_profile: "ovs"
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  # role: arn:aws:iam::969069172541:role/fe_lambda_execution
  profile: ${self:custom.aws_profile} # aws credentials profile to use
  region: ${opt:region, 'eu-central-1'}
  apiGateway:
    minimumCompressionSize: 0
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: PRODUCTION

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - "lambda:InvokeFunction"
    Resource:
      "*"
  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
      - schedule:
        name: lambda-warmer-schedule
        rate: rate(5 minutes)
        enabled: true
        input:
          warmer: true
          concurrency: 1
