service:
  name: omniview-backend
app: ovs-backend
org: colorfy

custom:
  aws_profile: "ovs"
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  # role: arn:aws:iam::969069172541:role/fe_lambda_execution
  profile: ${self:custom.aws_profile} # aws credentials profile to use
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 0
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: PRODUCTION

  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
