service:
  name: omniview-backend
app: ovs-backend
org: colorfy

custom:
  aws_profile: "ovs"
  warmup:
    enabled: true
    
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.aws_profile} # aws credentials profile to use
  region: ${opt:region, 'eu-central-1'}
  apiGateway:
    minimumCompressionSize: 0
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: PRODUCTION

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - "lambda:InvokeFunction"
    Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${self:provider.stage}-*
  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
